### ISSUE TITLE
Note: Calendar Data Structure

### ISSUE THREAD

**Issue by egeldenhuys** [team-andromeda/wall-pi#2]
Browser to https://developer.microsoft.com/en-us/graph/graph-explorer and authenticate.

Modify Permissions to include the scopes 'User.Read', 'Calendars.Read', 'Calendars.Read.Shared'

Execute query `https://graph.microsoft.com/v1.0/users/assembly@bbd.co.za/calendar/events`

**Comment by JasP19** [comment]
Run this query to obtain all events on the specified day:
https://graph.microsoft.com/v1.0/users/assembly@bbd.co.za/calendar/events?$filter=start/dateTime ge '2018-02-01T00:00' and start/dateTime le '2018-02-02T00:00'
